---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
---


```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(leaflet)
library(plotly)
library(flexdashboard)
library(lubridate)
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE)
```

```{r , include=FALSE}
data("rest_inspec") 
korean_rest = 
  rest_inspec %>%
  select(boro, cuisine_description, critical_flag, score, grade, violation_description, inspection_date) %>%
  filter (cuisine_description == "Korean") %>%
  mutate(inspection_date = as_date(inspection_date))
korean_rest
```

Column {data-width=650}
-----------------------------------------------------------------------

## Chart A

```{r}
korean_rest %>%
  mutate(text_label = str_c(boro,"\nBoro: ", grade)) %>%
  plot_ly(
    x = ~ inspection_date, y = ~score, type = "scatter", mode = "markers",
    color = ~boro, text = ~text_label, alpha = 0.5, colors = "viridis")%>% 
layout(
    xaxis = list(title = "Boro"),
    yaxis = list(title = "Score"),
    title = "Score of Korean Resturuant in Diffreent Boros of NYC"
  )
```

Column {data-width=350}
-----------------------------------------------------------------------

## Chart B

```{r }
korean_rest %>% 
  mutate(boro = fct_reorder(boro, score)) %>% 
  plot_ly(y = ~score, color = ~boro, type = "box", colors = "viridis")%>% 
layout(
    xaxis = list(title = "Boro"),
    yaxis = list(title = "Score"),
    title = "Score of Korean Resturuant in Diffreent Boros of NYC"
    )
```


## Chart C

```{r}
korean_rest %>% 
  count(boro) %>% 
  mutate(boro= fct_reorder(boro, n)) %>% 
  plot_ly(x = ~boro, y = ~n, color = ~boro, type = "bar", colors = "viridis")%>%
layout(
    xaxis = list(title = "Boro"),
    title = "Number of Korean Resturuant in Diffreent Boros of NYC"
    )
```
