---
title: "Shuhong's Website"
output: 
  html_document:
    toc: true
    toc_float: true
---

```{r}
knitr::opts_chunk$set(fig.path='Figs/',
                      echo=FALSE, warning=FALSE, message=FALSE)
```


```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(plotly)
library(lubridate)
```

I want to know about the Korean restaurant' circumstance in NYC so I choose to analyze the NYC Restaurant Inspection Results dataset from the p8105.datasets.  

```{r , include=FALSE}
 data("rest_inspec") 
```

```{r}
korean_rest = 
  rest_inspec %>%
  select(boro, cuisine_description, critical_flag, score, grade, zipcode, inspection_date) %>%
  filter (cuisine_description == "Korean") %>%
  mutate(cuisine_description = as_factor(cuisine_description)) %>%
  mutate(critical_flag = as_factor(critical_flag)) %>%
  mutate(inspection_date = as_date(inspection_date))
korean_rest
```

### Use the scatterplot to track the score of of Korean resruruant based on boro.

```{r}
korean_rest %>%
  mutate(text_label = str_c(boro,"\nBoro: ", grade)) %>% 
  plot_ly(
    x = ~ boro, y = ~score, type = "scatter", mode = "markers",
    color = ~boro, text = ~text_label, alpha = 0.5, colors = "viridis")%>% 
layout(
    xaxis = list(title = "Boro"),
    yaxis = list(title = "Score"),
    title = "Score of Korean Resturuant in Diffreent Borox of NYC"
  )
```

We can see only 2 Korean restaurant in Bronx.

### To be more clear about the median, mean and Q1Q3 of the score, I made the boxlot:

```{r}
korean_rest %>% 
  mutate(boro = fct_reorder(boro, score)) %>% 
  plot_ly(y = ~score, color = ~boro, type = "box", colors = "viridis")%>% 
layout(
    xaxis = list(title = "Boro"),
    yaxis = list(title = "Score"),
    title = "Score of Korean Resturuant in Diffreent Borox of NYC"
    )
```



